# This pipeline will delete all resources in Resource Group defined in the variable resourceGroupName.

#
# The following variables need to be provided to the pipeline:
# - resourceGroupName            : name for the Resource Group where the vm will be created.
# - virtualMachineName           : name for the virtual machine.
# - vmNIC                        : Name for NIC.
# - vmNSG                        : Name for NSG.
# - vmVNET                        : Name for VNET
# - osDiskName                   : Name for Managed Disk containing the OS.
# - dataDiskName                 : Name for Managed Disk containing the data.
# - subecriptionId               : ID for subscription.
# - token                        : Token for container (snapshot). Secret
# - tokenSA                      : Token for Storage account. Secret
# - containerName                : Name for container.
# - storageAccount               : Name for Storage account,

# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'AzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  resourceGroupName: "snapshot-rg"
  virtualMachineName: "easec-vm"
  vmNIC: "easec-vmVMNic"
  vmNSG: "easec-vmNSG"
  vmVNET: "easec-vmVNET"
  osDiskName: "easec-vm_OsDisk_1_man"
  dataDiskName: "easec-vm_DataDisk_1_man"
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  storageAccount: "snapshottestsa"
  containerName: "snapshot"

stages:
- stage: Delete_vm
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshot-rg'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az group delete --name "$(resourceGroupName)" --force-deletion-types Microsoft.Compute/virtualMachines --no-wait --yes

- stage: Delete_blobs_and_container
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshottestsa'
         scriptType: bash
         scriptLocation: inlineScript
         inlineScript: 
          $Env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
          $Env:AZCOPY_MSI_CLIENT_ID="$(clientId)"
          azcopy login status 
          az storage blob delete-batch --source "$(containerName)" --account-name "$(storageAccount)" --auth-mode login
          az storage container delete --account-name "$(storageAccount)" --auth-mode login --name "$(containerName)"