# This pipeline will delete all resources for the archive solution, including virtual machines, and container with blobs.

#
#

# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'connection_snapshot-rg' and 'connection_snapshottestsa'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
- group: variable_iScaleArchive

stages:
- stage: Delete_vm
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: "connection_snapshot-rg"
         scriptType: "pscore"
         scriptLocation: "inlineScript"
         inlineScript: |
          az group delete --name "$(resourceGroupName)" --force-deletion-types Microsoft.Compute/virtualMachines --no-wait --yes

- stage: Delete_blobs_and_container
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: "connection_snapshottestsa"
         scriptType: "pscore"
         scriptLocation: "inlineScript"
         inlineScript: |
          $Env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
          $Env:AZCOPY_MSI_CLIENT_ID="$(clientId)"
          az storage blob delete-batch --source "$(containerName)" --account-name "$(storageAccount)" --auth-mode login
          az storage container delete --account-name "$(storageAccount)" --auth-mode login --name "$(containerName)"

- stage: Disable_logic_app
  jobs:
  - job:
    steps:
    - task: AzurePowerShell@5
      inputs:
       azureSubscription: "connection_subscription"
       azurePowerShellVersion: "LatestVersion"
       scriptType: "InlineScript"
       Inline: |
        Set-AzLogicApp -ResourceGroupName "$(resourceGroupResources)" -Name "$(logicAppName)" -State "Disabled"