# This pipeline will delete all resources for the archive solution, including virtual machines, and container with blobs.
#
# The pipeline will also disable the Logic App.
#
#
# The variables is provided by Variable group with the name: variable_iScaleArchive
#
#
# Pipeline are used with User assigned managed identity
#
# This pipeline also expects Azure (Resource Manager) service connections in Azure DevOps with the name 'connection_snapshottestsa' and 'connection_subscription' , using Workload Identity federation (manual). This service connections must have been set up in the Project Settings.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
- group: variable_iScaleArchive

stages:
- stage: delete_vm
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: "connection_snapshot-rg"
         scriptType: "pscore"
         scriptLocation: "inlineScript"
         inlineScript: |
          az group delete --name "$(resourceGroupName)" --force-deletion-types Microsoft.Compute/virtualMachines --no-wait --yes

- stage: delete_blobs_and_container
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: "connection_snapshottestsa"
         scriptType: "pscore"
         scriptLocation: "inlineScript"
         inlineScript: |
          $Env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
          $Env:AZCOPY_MSI_CLIENT_ID="$(clientId)"
          az storage blob delete-batch --source "$(containerName)" --account-name "$(storageAccount)" --auth-mode login
          az storage container delete --account-name "$(storageAccount)" --auth-mode login --name "$(containerName)"

- stage: disable_logic_app
  jobs:
  - job:
    steps:
    - task: AzurePowerShell@5
      inputs:
       azureSubscription: "connection_subscription"
       azurePowerShellVersion: "LatestVersion"
       scriptType: "InlineScript"
       Inline: |
        Set-AzLogicApp -ResourceGroupName "$(resourceGroupResources)" -Name "$(logicAppName)" -State "Disabled" -Force